---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.nttdata.com
  resources:
  - awsrdsdemoinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.nttdata.com
  resources:
  - awsrdsdemoinstances/finalizers
  verbs:
  - update
- apiGroups:
  - aws.nttdata.com
  resources:
  - awsrdsdemoinstances/status
  verbs:
  - get
  - patch
  - update
