apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-aws-rds-demo
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::063010046250:role/aboczekAmazonEKSServiceAccountRDSRole
