apiVersion: aws.nttdata.com/v1alpha1
kind: AwsRDSDemoInstance
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-aws-rds-demo
    app.kubernetes.io/managed-by: kustomize
  name: awsrdsdemoinstance-sample
spec:
  # TODO(user): Add fields here
