apiVersion: aws.nttdata.com/v1alpha1
kind: AwsRDSDemoInstance
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-aws-rds-demo
    app.kubernetes.io/managed-by: kustomize
  name: awsrdsdemoinstance-dev
spec:
  dbInstanceClass: "db.t3.micro"
  engine: "postgres"
  engineVersion: "17.2"
  dbName: "k8soperatorawsrdsdemo"
  stage: "dev"
  credentialSecretName: "postgres-secret"