apiVersion: v1
kind: Pod
metadata:
  name: rds-test
spec:
  serviceAccountName: k8s-operator-aws-rds-demo-controller-manager
  containers:
  - name: aws-cli
    image: amazonlinux
    command: ["sleep", "3600"]
